apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: taxsystem
  labels:
    app: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service
          image: taxsystem-bank-service:latest
          imagePullPolicy: Never
          env:
            - name: TAXSYSTEM_DB_CONNECTION_WRITE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: BANK_DB_CONNECTION_WRITE
            - name: TAXSYSTEM_DB_CONNECTION_READ
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: BANK_DB_CONNECTION_READ
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: taxsystem
spec:
  selector:
    app: bank-service
  ports:
    - port: 80
      targetPort: 8080
