apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: tax-system
type: Opaque
stringData:
  POSTGRES_USER: "taxsystem"
  POSTGRES_PASSWORD: "taxsystem-dev"
  CITIZEN_DB_CONNECTION: "Host=postgres;Port=5432;Database=citizen_db;Username=taxsystem;Password=taxsystem-dev"
  COMPANY_DB_CONNECTION: "Host=postgres;Port=5432;Database=company_db;Username=taxsystem;Password=taxsystem-dev"
  BANK_DB_CONNECTION: "Host=postgres;Port=5432;Database=bank_db;Username=taxsystem;Password=taxsystem-dev"
  STATEMENT_DB_CONNECTION: "Host=postgres;Port=5432;Database=statement_db;Username=taxsystem;Password=taxsystem-dev"

