apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: tax-system
data:
  init.sql: |
    CREATE DATABASE citizen_db;
    CREATE DATABASE company_db;
    CREATE DATABASE bank_db;
    CREATE DATABASE statement_db;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: tax-system
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          args:
            - "-c"
            - "shared_buffers=64MB"
            - "-c"
            - "work_mem=4MB"
            - "-c"
            - "max_connections=50"
            - "-c"
            - "fsync=on"
            - "-c"
            - "synchronous_commit=on"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - "taxsystem"
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - "taxsystem"
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tax-system
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

