apiVersion: apps/v1
kind: Deployment
metadata:
  name: statementgenerator-service
  namespace: tax-system
  labels:
    app: statementgenerator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statementgenerator-service
  template:
    metadata:
      labels:
        app: statementgenerator-service
    spec:
      containers:
        - name: statementgenerator-service
          image: taxsystem-statementgenerator-service:latest
          imagePullPolicy: Never
          env:
            - name: TAXSYSTEM_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: STATEMENT_DB_CONNECTION
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: statementgenerator-service
  namespace: tax-system
spec:
  selector:
    app: statementgenerator-service
  ports:
    - port: 80
      targetPort: 8080

