apiVersion: v1
kind: Namespace
metadata:
  name: tax-system
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: taxsystem-data
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/taxsystem
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taxsystem-data
  namespace: tax-system
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: taxsystem-data

