[managed_nodes]
controlnode ansible_connection=local
worker1 ansible_host=172.16.0.5 ansible_user=azureuser
worker2 ansible_host=172.16.0.6 ansible_user=azureuser

[managed_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
