apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik

spec:
  interval: 30m

  chart:
    spec:
      chart: traefik
      version: "41.0.2"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 6h

  install:
    createNamespace: false
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:

    deployment:
      replicas: 2
      podLabels:
        spread: traefik

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            spread: traefik

    hostNetwork: false

    service:
      enabled: true
      spec:
        type: ClusterIP

    ingressClass:
      enabled: true
      isDefaultClass: true

    providers:
      kubernetesIngress:
        enabled: true
      kubernetesCRD:
        enabled: true

    ports:
      web:
        expose:
          default: true
        exposedPort: 80
        protocol: TCP

      websecure:
        expose:
          default: true
        exposedPort: 443
        protocol: TCP

    # logs:
    #   general:
    #     level: INFO
