apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: taxsystem
  labels:
    app: bank-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
        workload-tier: taxsystem-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: DoNotSchedule
          matchLabelKeys:
            - pod-template-hash
          labelSelector:
            matchLabels:
              app: bank-service
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              workload-tier: taxsystem-app
      containers:
        - name: bank-service
          image: ghcr.io/nicodm13/k8s-ansible-project/taxsystem-bank-service:b163d447a102484c5d903779c0e6ae29747698d1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 500Mi
          env:
            - name: TAXSYSTEM_DB_CONNECTION_WRITE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: BANK_DB_CONNECTION_WRITE
            - name: TAXSYSTEM_DB_CONNECTION_READ
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: BANK_DB_CONNECTION_READ
            - name: RABBITMQ_HOST
              value: "rabbitmq.taxsystem.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "taxsystem"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: taxsystem
spec:
  selector:
    app: bank-service
  ports:
    - port: 80
      targetPort: 8080
