apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citizen-service
  namespace: taxsystem
  labels:
    app: citizen-service
spec:
  serviceName: citizen-service-headless
  replicas: 2
  selector:
    matchLabels:
      app: citizen-service
  template:
    metadata:
      labels:
        app: citizen-service
        workload-tier: taxsystem-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: citizen-service
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              workload-tier: taxsystem-app
      containers:
        - name: citizen-service
          image: ghcr.io/nicodm13/k8s-ansible-project/taxsystem-citizen-service:b1a5839277780329e601cceccd4a06b23b6fa765
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 600Mi
          env:
            - name: TAXSYSTEM_DATA_PATH
              value: "/var/lib/taxsystem"
            - name: TAXSYSTEM_DB_CONNECTION_WRITE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: CITIZEN_DB_CONNECTION_WRITE
            - name: TAXSYSTEM_DB_CONNECTION_READ
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: CITIZEN_DB_CONNECTION_READ
            - name: RABBITMQ_HOST
              value: "rabbitmq.taxsystem.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "taxsystem"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/taxsystem
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: citizen-service
  namespace: taxsystem
spec:
  selector:
    app: citizen-service
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: citizen-service-headless
  namespace: taxsystem
spec:
  clusterIP: None
  selector:
    app: citizen-service
  ports:
    - port: 80
      targetPort: 8080
