apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: taxsystem
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ghcr.io/nicodm13/k8s-ansible-project/taxsystem-client:9e85dfd44f52a449249b99c0a44ba77bd5f3e933
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: RABBITMQ_HOST
              value: "rabbitmq.taxsystem.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "taxsystem"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: taxsystem
spec:
  selector:
    app: client
  ports:
    - port: 8080
      targetPort: 8080
