apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
  namespace: taxsystem
  labels:
    app: company-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
        workload-tier: taxsystem-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: company-service
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              workload-tier: taxsystem-app
      containers:
        - name: company-service
          image: ghcr.io/nicodm13/k8s-ansible-project/taxsystem-company-service:59ecc7155eb6d47986837fa40b221ac3d83b28ce
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 600Mi
          env:
            - name: TAXSYSTEM_DB_CONNECTION_WRITE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: COMPANY_DB_CONNECTION_WRITE
            - name: TAXSYSTEM_DB_CONNECTION_READ
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: COMPANY_DB_CONNECTION_READ
            - name: RABBITMQ_HOST
              value: "rabbitmq.taxsystem.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "taxsystem"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: taxsystem
spec:
  selector:
    app: company-service
  ports:
    - port: 80
      targetPort: 8080
