apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - client.yaml
  - citizen-service.yaml
  - company-service.yaml
  - bank-service.yaml
  - statementgenerator-service.yaml
