apiVersion: apps/v1
kind: Deployment
metadata:
  name: statementgenerator-service
  namespace: taxsystem
  labels:
    app: statementgenerator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statementgenerator-service
  template:
    metadata:
      labels:
        app: statementgenerator-service
        workload-tier: taxsystem-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: statementgenerator-service
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              workload-tier: taxsystem-app
      containers:
        - name: statementgenerator-service
          image: ghcr.io/nicodm13/k8s-ansible-project/taxsystem-statementgenerator-service:d4340e01a927074531a6f353904c18fe360f13b1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 800Mi
          env:
            - name: TAXSYSTEM_DB_CONNECTION_WRITE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: STATEMENT_DB_CONNECTION_WRITE
            - name: TAXSYSTEM_DB_CONNECTION_READ
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: STATEMENT_DB_CONNECTION_READ
            - name: RABBITMQ_HOST
              value: "rabbitmq.taxsystem.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "taxsystem"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: statementgenerator-service
  namespace: taxsystem
spec:
  selector:
    app: statementgenerator-service
  ports:
    - port: 80
      targetPort: 8080
