apiVersion: apps/v1
kind: Deployment
metadata:
  name: statementgenerator-service
  namespace: taxsystem
  labels:
    app: statementgenerator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statementgenerator-service
  template:
    metadata:
      labels:
        app: statementgenerator-service
    spec:
      containers:
        - name: statementgenerator-service
          image: ghcr.io/nicodm13/k8s-ansible-project/taxsystem-statementgenerator-service:9d62b5d229249809a432ee3168a9a2ca63846c6f
          imagePullPolicy: IfNotPresent
          env:
            - name: TAXSYSTEM_DATA_PATH
              value: "/var/lib/taxsystem"
            - name: TAXSYSTEM_DB_CONNECTION_WRITE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: STATEMENT_DB_CONNECTION_WRITE
            - name: TAXSYSTEM_DB_CONNECTION_READ
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: STATEMENT_DB_CONNECTION_READ
            - name: RABBITMQ_HOST
              value: "rabbitmq.taxsystem.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "taxsystem"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/taxsystem
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: taxsystem-statement-data
---
apiVersion: v1
kind: Service
metadata:
  name: statementgenerator-service
  namespace: taxsystem
spec:
  selector:
    app: statementgenerator-service
  ports:
    - port: 80
      targetPort: 8080
